apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-consumer-deployment
spec:
  replicas: 1  # Puedes ajustar el número de réplicas según sea necesario
  selector:
    matchLabels:
      app: customer-consumer
  template:
    metadata:
      labels:
        app: customer-consumer
    spec:
      containers:
      - name: customer-consumer
        image: santiagosanchez03/test_consumer  # Cambia esta línea por tu imagen en Docker Hub o el nombre de la imagen local
        ports:
        - containerPort: 3000  # Si es necesario, ajusta el puerto según el puerto expuesto en la app
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"  # Reemplaza 'kafka-service' con el nombre de tu servicio Kafka en Kubernetes
        - name: KAFKA_TOPIC
          value: "univalle-ideas"  # Asegúrate de que el topic esté correcto
        - name: KAFKA_GROUP_ID
          value: "test-group"  # Asegúrate de que el grupo esté correcto
---
apiVersion: v1
kind: Service
metadata:
  name: customer-consumer-service
spec:
  selector:
    app: customer-consumer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # Este es el puerto en el contenedor
  type: ClusterIP  # Cambia a NodePort si quieres acceso fuera del clúster
